'use strict';

const icons = () => ({
  add:       'fas fa-plus',
  home:      'fas fa-home',
  test:      'fas fa-cloud-download-alt',
  created:   'fas fa-flag-checkered',
  built:     'fas fa-flag-checkered',
  start:     'fas fa-tint', // water drop
  on:        'fas fa-arrow-right',
  off:       'fas fa-times-circle',
  dismantled:'fas fa-times-circle',
  end:       'fas fa-arrow-left',
  cassette:  'fas fa-inbox',
  component: 'fas fa-puzzle-piece',
  slope:     'fas fa-level-up-alt', // _|^
  rain:      'fas fa-shower',       // showerhead
  shower:    'fas fa-shower',
  notes:     'fas fa-comment-alt',
  raindrop:  'fas fa-tint', // water drop
  absorb:    'fas fa-tint', // water drop
  stopwatch: 'fas fa-stopwatch',
  runoff:    'fas fa-tint', // water drop
  clock:     'fas fa-clock',
  retention: 'fas fa-glass-martini',
  delay:     'fas fa-hand-paper', // halt hand signal
  label:     'fas fa-tags',
  size:      'fas fa-object-group',
  layers:    'fas fa-bars',
  scale:     'fas fa-weight',
  plants:    'fas fa-leaf',
  media:     'fas fa-braille',
  thickness: 'fas fa-text-height',
  zones:     'fas fa-share-alt',
  login:     'fas fa-user-plus',
  logout:    'fas fa-user-times',
  monitor:   'fas fa-heartbeat',
  contain:   'fas fa-inbox',
  check:     'fas fa-check',
  refresh:   'fas fa-sync',
  reorder:   'fas fa-retweet',
  up:        'fas fa-arrow-up',
  dn:        'fas fa-arrow-down',
  close:     'fas fa-times',
  trash:     'fas fa-trash-alt',
  lock:      'fas fa-lock',
  unlock:    'fas fa-unlock',
  save:      'fas fa-save',
  error:     'fas fa-exclamation-triangle',
  paper:     'fas fa-image',
  print:     'fas fa-file',
  question:  'fas fa-question',
  search:    'fas fa-search',
  right:     'fas fa-caret-right',
  left:      'fas fa-caret-left',
  pdf:       'fas fa-file-pdf',
  file:      'fas fa-file-alt',
  pressure:  'fas fa-bomb',
  temperature:'fas fa-thermometer-quarter',
  table:     'fas fa-table',
  edit:      'fas fa-edit',
  download:  'fas fa-download',
  graph:     'fas fa-chart-line',
  graph2:    'fas fa-chart-area',
  pie:       'fas fa-chart-pie',
  globe:     'fas fa-globe',
  cog:       'fa fa-cog',
  overspray: 'fas fa-spray-can',
  sun:       'fas fa-sun',
  yAxis:     'fas fa-arrows-alt-v',
  lab:       'fas fa-flask',
});

const fun = () => ({
  puzzle:     'fas fa-puzzle-piece',
  shower:     'fas fa-shower', 
  raindrop:   'fas fa-tint', 
  martini:    'fas fa-glass-martini',
  weight:     'fas fa-weight',
  plants:     'fas fa-leaf',
  heartbeat:  'fas fa-heartbeat',
  bomb:       'fas fa-bomb',
  anchor:     'fas fa-anchor',
  apple:      'fab fa-apple',
  justice:    'fas fa-balance-scale',
  bell:       'fas fa-bell',
  cake:       'fas fa-birthday-cake',
  binoculars: 'fas fa-binoculars',
  bowling:    'fas fa-bowling-ball',
  bug:        'fas fa-bug',
  chess:      'fas fa-chess',
  child:      'fas fa-child',
  bicycle:    'fas fa-bicycle',
  bullhorn:   'fas fa-bullhorn',
  bath:       'fas fa-bath',
  battery:    'fas fa-battery-half',
});

module.exports = { icons, fun } ;